/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.5.1/userguide/multi_project_builds.html
 */

rootProject.name = "VIS"
include(
        ":java:HelloWorld",
        ":cpp:HelloWorld",
        "socket:cpp:Hello",
        "socket:cpp:Primitive_SocketServer",
        "socket:cpp:Primitive_SocketClient",
        "socket:cpp:Echo_SocketServer",
        "socket:cpp:UDP_SocketServer",
        "socket:cpp:UDP_SocketClient",
        "socket:cpp:Ipv6_SocketServer",
        "socket:cpp:Ipv6_SocketClient",
        "socket:cpp:Environment_SocketServer",
        "socket:cpp:SocketClientTest",
        "socket:java:Echo_SocketClient",
        "socket:java:Echo_SocketServer",
        "socket:java:Environment_SocketClient",
        "general:EnvironmentI",
        "socket:cpp:Http_SocketServer")
include("rmi")
include("rmi:Hello_RmiInterface")
findProject(":rmi:Hello_RmiInterface")?.name = "Hello_RmiInterface"
include("rmi:Hello_RmiServer")
findProject(":rmi:Hello_RmiServer")?.name = "Hello_RmiServer"
include("rmi:Hello_RmiClient")
findProject(":rmi:Hello_RmiClient")?.name = "Hello_RmiClient"
include("rmi:Environment_RmiServer")
findProject(":rmi:Environment_RmiServer")?.name = "Environment_RmiServer"
include("rmi:Environment_RmiClient")
findProject(":rmi:Environment_RmiClient")?.name = "Environment_RmiClient"
include("servlet")
include("servlet:Hello_Servlet")
findProject(":servlet:Hello_Servlet")?.name = "Hello_Servlet"
include("servlet:Info_Servlet")
findProject(":servlet:Info_Servlet")?.name = "Info_Servlet"
include("servlet:Session_Servlet")
findProject(":servlet:Session_Servlet")?.name = "Session_Servlet"
include("servlet:EnvironmentService_Servlet")
findProject(":servlet:EnvironmentService_Servlet")?.name = "EnvironmentService_Servlet"
include("jaxb:BruteForce")
findProject(":jaxb:BruteForce")?.name = "BruteForce"
include("jaxb:parser:XML:untitled")
findProject(":jaxb:parser:XML:untitled")?.name = "untitled"
include("jaxb:parser:XML")
findProject(":jaxb:parser:XML")?.name = "XML"
include("jaxb:parser:JSON")
findProject(":jaxb:parser:JSON")?.name = "JSON"
include("jaxb:XML")
findProject(":jaxb:XML")?.name = "XML"
include("jaxb:JSON")
findProject(":jaxb:JSON")?.name = "JSON"
include("jaxb")
include("jaxb")
include("jaxb:BruteForce")
findProject(":jaxb:BruteForce")?.name = "BruteForce"
include("jaxb:parser:XML")
findProject(":jaxb:parser:XML")?.name = "XML"
include("parser:JSON")
findProject(":parser:JSON")?.name = "JSON"
include("jaxb:parser:JSON")
findProject(":jaxb:parser:JSON")?.name = "JSON"
include("jaxb:XML")
findProject(":jaxb:XML")?.name = "XML"
include("jaxb:JSON")
findProject(":jaxb:JSON")?.name = "JSON"
include("jaxb:parser:XML")
findProject(":jaxb:parser:XML")?.name = "XML"
include("rest")
include("rest:Hello_RestServer")
findProject(":rest:Hello_RestServer")?.name = "Hello_RestServer"
include("rest:Environment_RestServer")
findProject(":rest:Environment_RestServer")?.name = "Environment_RestServer"
include("rest:Environment_RestClient")
findProject(":rest:Environment_RestClient")?.name = "Environment_RestClient"
